---
- name: install packages required by apt
  become: yes
  package:
    name: apt-transport-https
    state: present

- name: add apt key for php7
  become: yes
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: add php sources
  become: yes
  template:
    src: php.list
    dest: /etc/apt/sources.list.d/php.list
  register: result

- name: update apt
  become: yes
  apt:
    update_cache: yes
  when: result.changed

- name: install php cli
  become: yes
  package:
    name: php7.2-cli,php7.2-fpm
    state: present
  notify: restart php fpm 7.2

- name: install php extensions
  become: yes
  package:
    name: "{{ php_extensions }}"
    state: present
  notify: restart php fpm 7.2

- name: ensure timezone is set in fpm php.ini
  become: yes
  lineinfile:
    dest: /etc/php/7.2/fpm/php.ini
    regexp: 'date.timezone ='
    line: 'date.timezone = {{ php_timezone }}'
  notify: restart php fpm 7.2

- name: Set max execution time
  become: yes
  lineinfile:
    dest: /etc/php/7.2/fpm/php.ini
    regexp: ';?max_execution_time = \d+'
    line: 'max_execution_time = 300'
  notify: restart php fpm 7.2

- name: enabling opcache
  become: yes
  lineinfile:
    dest: /etc/php/7.2/fpm/php.ini
    regexp: ';?opcache.enable=\d'
    line: 'opcache.enable=1'
  notify: restart php fpm 7.2

- name: increase max file upload size
  become: yes
  lineinfile:
    dest: /etc/php/7.2/fpm/php.ini
    regexp: 'upload_max_filesize ?='
    line: 'upload_max_filesize = 20M'
  notify: restart php fpm 7.2

- name: set session cookie name
  become: yes
  lineinfile:
    dest: /etc/php/7.2/fpm/php.ini
    regexp: 'session.name ?='
    line: 'session.name = rp'
  notify: restart php fpm 7.2

- name: set secure session cookies
  become: yes
  lineinfile:
    dest: /etc/php/7.2/fpm/php.ini
    regexp: 'session.cookie_secure ?='
    line: 'session.cookie_secure = 1'
  notify: restart php fpm 7.2

- name: set http only session cookies
  become: yes
  lineinfile:
    dest: /etc/php/7.2/fpm/php.ini
    regexp: 'session.cookie_httponly ?='
    line: 'session.cookie_httponly = 1'
  notify: restart php fpm 7.2

- name: Set permissions on socket - owner
  become: yes
  lineinfile:
    dest: /etc/php/7.2/fpm/pool.d/www.conf
    state: present
    regexp: '^;?listen.owner'
    line: 'listen.owner = www-data'
  notify: restart php fpm 7.2

- name: Set permissions on socket - group
  become: yes
  lineinfile:
    dest: /etc/php/7.2/fpm/pool.d/www.conf
    state: present
    regexp: '^;?listen.group'
    line: 'listen.group = www-data'
  notify: restart php fpm 7.2

- name: Set permissions on socket - mode
  become: yes
  lineinfile:
    dest: /etc/php/7.2/fpm/pool.d/www.conf
    state: present
    regexp: '^;?listen.mode'
    line: 'listen.mode = 0660'
  notify: restart php fpm 7.2

- name: Set request timeout
  become: yes
  lineinfile:
    dest: /etc/php/7.2/fpm/pool.d/www.conf
    regexp: ';?request_terminate_timeout=\d'
    line: 'request_terminate_timeout=300'
  notify: restart php fpm 7.2

- include_tasks: redis.yml
...